### ISSUE TITLE
Getting `java.lang.IllegalStateException: cannot open system clipboard` when opening Editor

### ISSUE THREAD

**Issue by sdercolin** [sdercolin/vlabeler#14]
## Env
Windows 10, javaRuntimeVersion=16.0.2+7, appVersion=1.0.0-alpha19

## Reproduction rate
2/80

## Error log
```
[2022-09-06T13:22:23.180240500Z] Uncaught exception in Thread AWT-EventQueue-0: java.lang.IllegalStateException: cannot open system clipboard
	at java.desktop/sun.awt.windows.WClipboard.openClipboard(Native Method)
	at java.desktop/sun.awt.datatransfer.SunClipboard.getData(Unknown Source)
	at org.jetbrains.skiko.Actuals_awtKt.ClipboardManager_getText(Actuals.awt.kt:62)
	at org.jetbrains.skiko.ClipboardManager.getText(Platform.kt:28)
	at androidx.compose.ui.platform.PlatformClipboardManager.getText(PlatformClipboardManager.skiko.kt:26)
	at androidx.compose.foundation.text.ContextMenu_desktopKt$contextMenuItems$1.invoke(ContextMenu.desktop.kt:93)
	at androidx.compose.foundation.text.ContextMenu_desktopKt$contextMenuItems$1.invoke(ContextMenu.desktop.kt:72)
	at androidx.compose.foundation.ContextMenuData$allItemsSeq$1.invokeSuspend(ContextMenuProvider.desktop.kt:184)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
	at androidx.compose.foundation.ContextMenuData$allItems$2.invoke(ContextMenuProvider.desktop.kt:179)
	at androidx.compose.foundation.ContextMenuData$allItems$2.invoke(ContextMenuProvider.desktop.kt:178)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.foundation.ContextMenuData.getAllItems$foundation(ContextMenuProvider.desktop.kt:178)
	at androidx.compose.foundation.ContextMenuProvider_desktopKt$ContextMenuArea$2.invoke(ContextMenuProvider.desktop.kt:61)
	at androidx.compose.foundation.ContextMenuProvider_desktopKt$ContextMenuArea$2.invoke(ContextMenuProvider.desktop.kt:57)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.foundation.ContextMenuProvider_desktopKt$ContextMenuDataProvider$2.invoke(ContextMenuProvider.desktop.kt:94)
	at androidx.compose.foundation.ContextMenuProvider_desktopKt$ContextMenuDataProvider$2.invoke(ContextMenuProvider.desktop.kt:93)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.foundation.ContextMenuProvider_desktopKt.ContextMenuDataProvider(ContextMenuProvider.desktop.kt:91)
	at androidx.compose.foundation.ContextMenuProvider_desktopKt.ContextMenuArea(ContextMenuProvider.desktop.kt:57)
	at androidx.compose.foundation.text.ContextMenu_desktopKt.ContextMenuArea(ContextMenu.desktop.kt:43)
	at androidx.compose.foundation.text.CoreTextFieldKt.CoreTextFieldRootBox(CoreTextField.kt:618)
	at androidx.compose.foundation.text.CoreTextFieldKt.CoreTextField(CoreTextField.kt:532)
	at androidx.compose.foundation.text.BasicTextFieldKt.BasicTextField(BasicTextField.kt:151)
	at com.sdercolin.vlabeler.ui.common.SearchBarKt.SearchBar(SearchBar.kt:39)
	at com.sdercolin.vlabeler.ui.editor.EntryListKt.EntryList(EntryList.kt:91)
	at com.sdercolin.vlabeler.ui.editor.EditorKt$Editor$entryListCard$1$1.invoke(Editor.kt:92)
	at com.sdercolin.vlabeler.ui.editor.EditorKt$Editor$entryListCard$1$1.invoke(Editor.kt:91)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2351)
	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2641)
	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:137)
	at androidx.compose.material.CardKt.Card-F-jzlyU(Card.kt:68)
	at com.sdercolin.vlabeler.ui.editor.EditorKt$Editor$entryListCard$1.invoke(Editor.kt:87)
	at com.sdercolin.vlabeler.ui.editor.EditorKt$Editor$entryListCard$1.invoke(Editor.kt:85)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at com.sdercolin.vlabeler.ui.editor.EditorKt$Editor$splitPaneContent$1$1$2.invoke(Editor.kt:128)
	at com.sdercolin.vlabeler.ui.editor.EditorKt$Editor$splitPaneContent$1$1$2.invoke(Editor.kt:127)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at org.jetbrains.compose.splitpane.DesktopSplitPaneKt.SplitPane(DesktopSplitPane.kt:41)
	at org.jetbrains.compose.splitpane.SplitPaneKt.HorizontalSplitPane(SplitPane.kt:61)
	at com.sdercolin.vlabeler.ui.editor.EditorKt.Editor(Editor.kt:162)
	at com.sdercolin.vlabeler.ui.AppKt.App(App.kt:57)
	at com.sdercolin.vlabeler.ui.AppKt$App$5.invoke(App.kt)
	at com.sdercolin.vlabeler.ui.AppKt$App$5.invoke(App.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2351)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2618)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3205)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3183)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3183)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3148)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:746)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:411)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:303)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:302)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:99)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:79)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:302)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:507)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.update(Direct3DRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.access$update(Direct3DRedrawer.kt:10)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invokeSuspend(Direct3DRedrawer.kt:28)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by sdercolin** [comment]
https://github.com/JetBrains/skiko/pull/586

**Comment by sdercolin** [comment]
Fix in https://github.com/JetBrains/compose-jb/releases/tag/v1.2.0
