### ISSUE TITLE
[Not a bug] "Java heap space" error keeps happening then vLabeler crashes. Do I have enough RAM?

### ISSUE THREAD

**Issue by lottev1991** [sdercolin/vlabeler#35]
Hello. This isn't a bug but rather a question regarding a problem on my end. Oftentimes, when I've been working in vLabeler for a while, after some time the program just crashes. I have 8GB of RAM on my laptop and I am wondering if this is enough to run vLabeler. I can't really find any information on recommended specs so I'm curious. I do sometimes click on "Recycle memory" but I often forget. I'm not sure there's any other solution I can use for right now, unless I'm missing something.

**Comment by lottev1991** [comment]
I've since upgraded to 16GB RAM but the program still crashes from time to time. For what it's worth, here's a relevant log bit from a while ago:
```
[2024-01-23T13:46:06.304118800Z] Uncaught exception in Thread AWT-EventQueue-0: java.lang.OutOfMemoryError: Java heap space
[2024-01-23T13:46:06.304118800Z] 	at java.base/java.util.Arrays.copyOf(Unknown Source)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.JsonToStringWriter.ensureTotalCapacity(JsonToStringWriter.kt:132)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.JsonToStringWriter.ensureAdditionalCapacity(JsonToStringWriter.kt:125)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.JsonToStringWriter.write(JsonToStringWriter.kt:45)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.Composer.print(Composers.kt:33)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.ComposerWithPrettyPrint.nextItem(Composers.kt:88)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeElement(StreamingJsonEncoder.kt:141)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:79)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.model.Entry.write$Self(Entry.kt:22)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.model.Entry$$serializer.serialize(Entry.kt:22)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.model.Entry$$serializer.serialize(Entry.kt:22)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:228)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.internal.CollectionLikeSerializer.serialize(CollectionSerializers.kt:69)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:228)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.model.Module.write$Self(Module.kt:34)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.model.Module$$serializer.serialize(Module.kt:34)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.model.Module$$serializer.serialize(Module.kt:34)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:228)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.internal.CollectionLikeSerializer.serialize(CollectionSerializers.kt:69)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:228)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.model.Project.write$Self(Project.kt:49)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.model.Project$$serializer.serialize(Project.kt:49)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.model.Project$$serializer.serialize(Project.kt:49)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:228)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:28)
[2024-01-23T13:46:06.304118800Z] 	at kotlinx.serialization.json.Json.encodeToString(Json.kt:81)
[2024-01-23T13:46:06.304118800Z] 	at com.sdercolin.vlabeler.io.ProjectKt$saveProjectFile$2$1.invokeSuspend(Project.kt:370)
[2024-01-23T13:46:06.304118800Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

I also found this, could this be related too?
```
[2024-02-16T19:12:40.635470800Z] Uncaught exception in Thread AWT-EventQueue-0: kotlinx.coroutines.CompletionHandlerException: Exception in resume onCancellation handler for CancellableContinuation(DispatchedContinuation[FlushCoroutineDispatcher@109139c4, Continuation at androidx.compose.foundation.gestures.PressGestureScopeImpl.reset(TapGestureDetector.kt:365)@2f294d0c]){Completed}@6003122a
[2024-02-16T19:12:40.635470800Z] 	at kotlinx.coroutines.CancellableContinuationImpl.callOnCancellation(CancellableContinuationImpl.kt:264)
[2024-02-16T19:12:40.635470800Z] 	at kotlinx.coroutines.CompletedContinuation.invokeHandlers(CancellableContinuationImpl.kt:659)
[2024-02-16T19:12:40.635470800Z] 	at kotlinx.coroutines.CancellableContinuationImpl.cancelCompletedResult$kotlinx_coroutines_core(CancellableContinuationImpl.kt:180)
[2024-02-16T19:12:40.635470800Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
[2024-02-16T19:12:40.635470800Z] 	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:62)
[2024-02-16T19:12:40.635470800Z] 	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:57)
[2024-02-16T19:12:40.635470800Z] 	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:91)
[2024-02-16T19:12:40.635470800Z] 	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:37)
[2024-02-16T19:12:40.635470800Z] 	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:57)
[2024-02-16T19:12:40.635470800Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[2024-02-16T19:12:40.635470800Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
[2024-02-16T19:12:40.635470800Z] 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@4f14d720, androidx.compose.runtime.BroadcastFrameClock@6bfede38, StandaloneCoroutine{Cancelling}@547269b1, FlushCoroutineDispatcher@109139c4]
[2024-02-16T19:12:40.635470800Z] Caused by: java.lang.IllegalStateException: This mutex is not locked
[2024-02-16T19:12:40.635470800Z] 	at kotlinx.coroutines.sync.MutexImpl.unlock(Mutex.kt:213)
[2024-02-16T19:12:40.635470800Z] 	at kotlinx.coroutines.sync.MutexImpl$CancellableContinuationWithOwner$tryResume$token$1.invoke(Mutex.kt:261)
[2024-02-16T19:12:40.635470800Z] 	at kotlinx.coroutines.sync.MutexImpl$CancellableContinuationWithOwner$tryResume$token$1.invoke(Mutex.kt:258)
[2024-02-16T19:12:40.635470800Z] 	at kotlinx.coroutines.CancellableContinuationImpl.callOnCancellation(CancellableContinuationImpl.kt:259)
[2024-02-16T19:12:40.635470800Z] 	... 23 more
```

**Comment by sdercolin** [comment]
Thank you for the info!
The first log is the relevant one I think. It shows that the heap space is not enough when the program tries to save a project, which is very unexpected to me 😂 We usually face memory issues around audio data or graphs, but the project file should be small enough to be handled.
Some more questions:
- Is the crashing when you try to save the project (or auto-save)?
- Is it happening on a certain project?
  - Try making another project to see if it has the same problem
  - If possible, share the project file with me via email (sder.colin@gmail.com)

**Comment by lottev1991** [comment]
- I'm not sure whether its related to auto-save or not (it's not related to regular saving though, that I'm certain of). I could perhaps try to turn it off for a while and see if it stops happening.
- It's not related to any specific project, though it started happening more frequently while I was doing some NNSVS labeling.

**Comment by lottev1991** [comment]
Actually I think I know what the issue might've been, and it was my own fault (not entirely surprised there). I had my undo-redo history set extremely high, unnecessarily so. That's probably what was causing this. Don't do that folks, not worth it.
